# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b686297ee3666818278e319ef6bc19973bf1b46dc37e2c5ec674dd7fa3e75d9a556c08d49d138e98f9dd55d52695273880fb47aa2ab89d66bcca405b0a20b9e

test:
  secret_key_base: 93ca824c62152d3206d0975b8563c903b1ed440a92b29c4d135b28382407f1f1c06e424728d565aa1435186b2f63c1e5b38657cc88f5e57c4581c0f64d15c7df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
